# Generated by Django 6.0.2 on 2026-03-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znacka_a_model', models.CharField(max_length=100, verbose_name='Značka a model')),
                ('spz', models.CharField(max_length=20, unique=True, verbose_name='SPZ')),
                ('rok_vyroby', models.IntegerField(verbose_name='Rok výroby')),
                ('stav_tachometru', models.IntegerField(verbose_name='Stav tachometru')),
                ('prevodovka', models.CharField(max_length=50, verbose_name='Převodovka')),
                ('pocet_mist', models.IntegerField(verbose_name='Počet míst')),
            ],
            options={
                'verbose_name': 'Auto',
                'verbose_name_plural': 'Auta',
            },
        ),
        migrations.CreateModel(
            name='Uzivatel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=150, verbose_name='Jméno')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('heslo', models.CharField(max_length=128, verbose_name='Heslo')),
                ('role', models.CharField(max_length=50, verbose_name='Role')),
            ],
            options={
                'verbose_name': 'Uživatel',
                'verbose_name_plural': 'Uživatelé',
            },
        ),
        migrations.CreateModel(
            name='Rezervace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum_vyzvednuti', models.DateField(verbose_name='Datum vyzvednutí')),
                ('misto_vraceni', models.CharField(max_length=150, verbose_name='Místo vrácení')),
                ('typ_pojisteni', models.CharField(max_length=100, verbose_name='Typ pojištění')),
                ('stav', models.CharField(max_length=50, verbose_name='Stav')),
                ('auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.auto', verbose_name='Auto')),
                ('uzivatel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.uzivatel', verbose_name='Uživatel')),
            ],
            options={
                'verbose_name': 'Rezervace',
                'verbose_name_plural': 'Rezervace',
            },
        ),
    ]
